name: employee_ledger
description: "An elegant, offline-first employee ledger and team management progressive web and mobile application."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^2.0.0
  flutter_bloc: ^9.1.0
  path_provider: ^2.1.5
  equatable: ^3.0.0
  intl: ^0.20.2
  sembast: ^3.8.4+1
  path: ^1.9.1
  sembast_web: ^2.4.1
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  ios: true
  web: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
